version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    extra_hosts:
      - "dockerhost:192.168.0.16" #We must bind docker host to our local ip

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000