{
 "title": "Car Dashboard (1)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Battery Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "battery_temperature_battery_temperature"
    }
   ]
  },
  {
   "title": "Car Speed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    { "expr": "car_speed_car_speed" }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "engine_temperature_engine_temperature"
    }
   ]
  },
  {
   "title": "Battery Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "battery_usage_battery_usage" }
   ]
  }
 ]
}